# Generated by Django 6.0.3 on 2026-03-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name_af',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ar_dz',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ast',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_az',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_be',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_bg',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_bn',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_br',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_bs',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ca',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ckb',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_cs',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_cy',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_da',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_de',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_dsb',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_el',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_en_au',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_en_gb',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_eo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_es',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_es_ar',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_es_co',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_es_mx',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_es_ni',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_es_ve',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_et',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_eu',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_fa',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_fy',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ga',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_gd',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_gl',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_he',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_hi',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_hr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_hsb',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ht',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_hu',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ia',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ig',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ind',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_io',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_is',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_it',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ja',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ka',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_kab',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_km',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_kn',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ko',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ky',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_lb',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_lt',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_lv',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_mk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ml',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_mn',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_mr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ms',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_my',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_nb',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ne',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_nn',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_os',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_pa',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_pl',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_pt',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ro',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_sk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_sl',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_sq',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_sr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_sr_latn',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_sv',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_sw',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ta',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_te',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_tg',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_th',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_tk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_tr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_tt',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_udm',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ug',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ur',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_vi',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_zh_hans',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_zh_hant',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_af',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ar_dz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_be',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_bs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ckb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_cs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_da',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_dsb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_en_au',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_eo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_es_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_es_co',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_es_mx',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_es_ni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_es_ve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_et',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_eu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_fy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_gd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_gl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_hr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_hsb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ht',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_hu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_io',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_is',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_kab',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_km',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_lb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_lv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_mk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_mn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_my',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_nb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_nn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_pa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_sl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_sq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_sr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_sr_latn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_tg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_tk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_tt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_udm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_vi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='address_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ht',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
